apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dotnet3-webapi-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dotnet3-webapi-chart.name" . }}
    helm.sh/chart: {{ include "dotnet3-webapi-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dotnet3-webapi-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dotnet3-webapi-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
            # - name: https
            #   containerPort: 443
            #   protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.containers.livenessProbe }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.containers.readinessProbe }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
