apiVersion: v1
kind: Service
metadata:
  name: {{ include "dotnet3-webapi-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dotnet3-webapi-chart.name" . }}
    helm.sh/chart: {{ include "dotnet3-webapi-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
    # - port: {{ .Values.service.https }}
    #   targetPort: https
    #   protocol: TCP
    #   name: https
  selector:
    app.kubernetes.io/name: {{ include "dotnet3-webapi-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
